## Deep learning - Project 1

Given a Bank customer, can we build a classifier which can determine whether they will leave or not using Neural networks?

The points distribution for this case is as follows:

1. Read the dataset

2. Drop the columns which are unique for all users like IDs (2.5 points)

3. Distinguish the feature and target set (2.5 points)

4. Divide the data set into Train and test sets

5. Normalize the train and test data (2.5 points)

6. Initialize & build the model (10 points)

7. Optimize the model (5 points)

8. Predict the results using 0.5 as a threshold (5 points)

9. Print the Accuracy score and confusion matrix (2.5 points)

### Load tensorflow

In [1]:
import tensorflow as tf
tf.set_random_seed(42)

In [2]:
tf.__version__

'1.14.0'

### 1. Read the dataset

In [3]:
import pandas as pd

In [4]:
data = pd.read_csv('bank.csv')

### 2. Drop the columns which are unique for all users like IDs (2.5 points)

In [5]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
data.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [7]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
df = data.drop(columns=['RowNumber','CustomerId','Surname'])

In [9]:
df.Geography = pd.Categorical(df.Geography).codes
df.Gender = pd.Categorical(df.Gender).codes

In [10]:
df.head(10)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   
5          645          2       1   44       8  113755.78              2   
6          822          0       1   50       7       0.00              2   
7          376          1       0   29       4  115046.74              4   
8          501          0       1   44       4  142051.07              2   
9          684          0       1   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0  
5          1               0        149756.71       1  
6          1               1         10062.80       0  
7          1               0        119346.88       1  
8          0               1         74940.50       0  
9          1               1         71725.73       0

### 3. Distinguish the feature and target set (2.5 points)

In [11]:
x = df.drop(columns='Exited').astype('float32')
y = df["Exited"].astype('float32')

In [12]:
# Converting into One-hot vectors using Keras
from keras.utils import to_categorical
y = to_categorical(y)

Using TensorFlow backend.


In [13]:
y[:2]

array([[0., 1.],
       [1., 0.]], dtype=float32)

### 4. Divide the data set into Train and test sets

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
# Split the dataset in two parts
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [16]:
x_train.shape

(8000, 10)

In [17]:
y_train.shape

(8000, 2)

### 5. Normalize the train and test data (2.5 points)

In [18]:
from sklearn.preprocessing import Normalizer

Normalize = Normalizer()

x_train = Normalize.fit_transform(x_train)

x_test = Normalize.fit_transform(x_test)

In [19]:
x_train[:2]

array([[4.0712436e-03, 1.2207627e-05, 0.0000000e+00, 2.0752967e-04,
        3.0519070e-05, 0.0000000e+00, 1.2207627e-05, 6.1038136e-06,
        0.0000000e+00, 9.9999171e-01],
       [4.5039640e-03, 1.0547925e-05, 1.0547925e-05, 4.4301286e-04,
        1.0547925e-05, 7.9828304e-01, 1.0547925e-05, 1.0547925e-05,
        1.0547925e-05, 6.0226542e-01]], dtype=float32)

In [20]:
y_train[:2]

array([[1., 0.],
       [1., 0.]], dtype=float32)

### 6. Initialize & build the model (10 points)

In [21]:
#Initialize Sequential model
model_1 = tf.keras.models.Sequential()

#Adding 1st dence layer
model_1.add(tf.keras.layers.Dense(20, activation='sigmoid',input_shape=(10,)))

#Add 2nd hidden layer
model_1.add(tf.keras.layers.Dense(10, activation='sigmoid'))

#Adding OUTPUT layer
model_1.add(tf.keras.layers.Dense(2, activation='softmax'))

W1007 12:22:55.813936   412 deprecation.py:506] From C:\Users\hp\Anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


The sigmoid function is used for the two-class logistic regression, whereas the softmax function is used for the multiclass logistic regression (a.k.a. MaxEnt, multinomial logistic regression, softmax Regression, Maximum Entropy Classifier). with β=−(β0−β1)

Softmax function calculates the probabilities distribution of the event over 'n' different events. In general way of saying, this function will calculate the probabilities of each target class over all possible target classes.  The purpose of the softmax classification layer is simply to transform all the net activations in your final output layer to a series of values that can be interpreted as probabilities. To do this, the softmax function is applied onto the net outputs (without an activation function or bias)

we use softmax activation instead of sigmoid with the cross-entropy loss because softmax activation distributes the probability throughout each output node. But, since it is a binary classification, using sigmoid is same as softmax. For multi-class classification use sofmax with cross-entropy.

### 7. Optimize the model (5 points)

In [22]:
#Create optimizer with non-default learning rate
sgd_optimizer1 = tf.keras.optimizers.SGD(lr=0.3)

#Compile the model
model_1.compile(optimizer=sgd_optimizer1, loss='categorical_crossentropy', metrics=['accuracy'])

### Stochastic gradient descent(SGD)
In Keras, we can do this to have SGD + Nesterov enabled, it works well for shallow networks. keras. optimizers. SGD(lr=0.3)

In [23]:
model_1.fit(x_train,y_train,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 3s 385us/sample - loss: 0.5086 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 106us/sample - loss: 0.5074 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 95us/sample - loss: 0.5058 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.5057 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 77us/sample - loss: 0.5041 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 89us/sample - loss: 0.5038 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 63us/sample - loss: 0.5032 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 0s 61us/sample - loss: 0.5038 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 0s 56us/sample - loss: 0.5029 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 0s 54us/sample - loss: 0.5029 -

### 8. Predict the results using 0.5 as a threshold (5 points)

In [24]:
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [25]:
y_test_predict = model_1.predict(x_test)
y_test_predict = y_test_predict.argmax(axis=1)

The max function gives the largest possible value of f(x) for any x in the domain, which is the function value achieved by any element of the argmax. Unlike the argmax, the max function is unique since all elements of the argmax achieve the same value. However, the max may not exist because the argmax may be empty

In [26]:
y_test_predict = (model_1.predict_proba(x_test)[:,1] >= 0.5).astype('float32')

In [27]:
y_test_predict

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

### 9. Print the Accuracy score and confusion matrix (2.5 points)

In [28]:
y_test = y_test.argmax(axis=1)

In [29]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
accuracy = accuracy_score(y_test,y_test_predict)

In [31]:
print("The test accuracy percentage is :", accuracy*100 )

The test accuracy percentage is : 79.75


In [32]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_test_predict)

array([[1595,    0],
       [ 405,    0]], dtype=int64)

# Approach2 by using Rectified Liner Activation Function for First Hidden Layers

### The rectified linear activation function is a piecewise linear function that will output the input directly if is positive, otherwise, it will output zero.

In [33]:
data1 = pd.read_csv('bank.csv')

In [34]:
df1 = data.drop(columns=['RowNumber','CustomerId','Surname'])

In [35]:
x1 = df1.drop(columns='Exited')
y1 = df1["Exited"]

In [36]:
x1.head(2)

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619    France  Female   42       2      0.00              1   
1          608     Spain  Female   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58

In [37]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [38]:
labelencoder_X_1 = LabelEncoder()
x1['Geography'] = labelencoder_X_1.fit_transform(x1['Geography'])
labelencoder_X_2 = LabelEncoder()
x1['Gender'] = labelencoder_X_1.fit_transform(x1['Gender'])



In [39]:
onehotencoder = OneHotEncoder(categorical_features=[1])
x1 = onehotencoder.fit_transform(x1).toarray()
x1 = x1[:,1:]

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [40]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size=0.2, random_state=0)

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x1_train = sc.fit_transform(x1_train)
x1_test = sc.transform(x1_test)

In [42]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [43]:
# Initializing the ANN
classifier = Sequential()

W1007 12:24:20.554428   412 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [44]:
# Adding the input Layer and the first Hidden layer using the Rectifier Activation 
classifier.add(Dense(output_dim=6, init='uniform', activation='relu', input_dim=11))

# Adding the input Layer and the second Hidden layer using the Rectifier Activation 
classifier.add(Dense(output_dim=6, init='uniform', activation='relu'))

# Adding the output layer using Sigmoid
classifier.add(Dense(output_dim=1, init='uniform', activation='sigmoid'))


C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  
W1007 12:24:21.596860   412 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1007 12:24:21.769140   412 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """
C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoi

### ReLU stands for rectified linear unit, and is a type of activation function. Mathematically, it is defined as y = max(0, x). Visually, it looks like the following: ReLUs are the most commonly used activation function in neural networks, especially in CNNs.

In [45]:
# Compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])

W1007 12:24:22.634735   412 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W1007 12:24:22.747808   412 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W1007 12:24:22.795848   412 deprecation.py:323] From C:\Users\hp\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [46]:
# Fitting the ANN to training set
classifier.fit(x1_train, y1_train, batch_size=10, epochs=100)

W1007 12:24:24.667738   412 deprecation_wrapper.py:119] From C:\Users\hp\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/100
8000/8000 [==============================] - 7s 821us/step - loss: 0.4808 - acc: 0.7959
Epoch 2/100
8000/8000 [==============================] - 2s 299us/step - loss: 0.4261 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 281us/step - loss: 0.4209 - acc: 0.8039
Epoch 4/100
8000/8000 [==============================] - 2s 269us/step - loss: 0.4173 - acc: 0.8249
Epoch 5/100
8000/8000 [==============================] - 2s 269us/step - loss: 0.4155 - acc: 0.8285
Epoch 6/100
8000/8000 [==============================] - 2s 249us/step - loss: 0.4138 - acc: 0.8317
Epoch 7/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.4125 - acc: 0.8329
Epoch 8/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.4118 - acc: 0.8322
Epoch 9/100
8000/8000 [==============================] - 2s 249us/step - loss: 0.4105 - acc: 0.8315
Epoch 10/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.4095 - acc: 0.8339

### It has been observed that as the number of epoch increases accuracy is almost same and losses decreses upto certain level he it is almost same. 

In [47]:
# Prediciting the test results 
y1_pred = classifier.predict(x1_test)
y1_pred = (y1_pred > 0.5)
y1_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [48]:
# Confusion Matrix
confusion_matrix(y1_test, y1_pred)

array([[1530,   65],
       [ 246,  159]], dtype=int64)

In [49]:
# The confusion Matrix shows the accurac of 87%
(1557+177)/2000


0.867

### Summary of both approaches

The Approach1 has given the accuray of 79%. The activation function for Hidden layer was Sigmoid and output layer was sofmax

The Approach2 has given the accuracy of 87%. The activation function for Hidden layer was Rectifier and output layer was Sigmoid

### The sigmoid function is used for the two-class logistic regression, so in approach two we have used sigmoid which is giving output in two class (Customer will leave or not).whereas in approach one we have used the softmax function is used for the multiclass logistic regression (a.k.a. MaxEnt, multinomial logistic regression, softmax Regression, Maximum Entropy Classifier). with β=−(β0−β1).